name: convert
on:
  workflow_dispatch:
    inputs:
      id:
        description: The ID of the dump to convert
        required: true
        type: string

jobs:
  convert:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Cache download
        uses: actions/cache@v4
        with:
          path: download
          key: download-${{ inputs.id }}

      - name: Convert dump
        run: sudo ./convert "${{ inputs.id }}"
