name: convert
on:
  workflow_dispatch:
    inputs:
      id:
        description: The ID of the dump to convert
        required: true
        type: string
      bucket:
        description: S3 bucket name
        required: false
        default: trustify-dumps-ds4
        type: string
      region:
        description: S3 bucket region
        required: false
        default: eu-west-1
        type: string

jobs:
  convert:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Cache download
        uses: actions/cache@v4
        with:
          path: download
          key: download-${{ inputs.id }}

      - name: Convert dump
        env:
          S3_BUCKET: ${{ inputs.bucket }}
          S3_REGION: ${{ inputs.region }}
        run: sudo --preserve-env=S3_BUCKET,S3_REGION ./convert "${{ inputs.id }}"

      - name: Upload archive to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TRUSTIFY_S3_UPLOAD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TRUSTIFY_S3_UPLOAD_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.region }}
        run: aws s3 cp "${{ inputs.id }}.btrfs.zstd" "s3://${{ inputs.bucket }}/${{ inputs.id }}.btrfs.zstd"
